### ISSUE TITLE
unable to execute the front end file

### ISSUE THREAD

**Issue by meenareddy365** [Pradyoth-Rao/Short-term-load-forecasting#2]
When I try to execute ur code ..... I am facing errors in the front end file...the error is
AttributeError: module 'LR' has no attribute 'execLR'
what should I do about it??

**Comment by prajwalkk** [comment]
The front-end files are not needed to run the project. Just run the LR.py in python terminal directly. Else, surround the logic of LR.py with a function definition execLR(). I think it has to be done to all the other files as well if you are running them using the frontend files. Basically this project had no need for a front-end. So, we dropped the idea of rectifying it.
